app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    batch-size: 100
    thread-count: 4
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  database-access-type: jpa

bot:
  url: http://localhost:8080

api:
  github:
    url: https://api.github.com
  stackoverflow:
    url: https://api.stackexchange.com/2.3

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
