app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    batch-size: 100
    thread-count: 4
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  database-access-type: jpa
  kafka:
    updates-topic-name: updates
  transport-order:
    - http
    - kafka

client:
  bot-url: http://localhost:8080
  github-url: https://api.github.com
  stackoverflow-url: https://api.stackexchange.com/2.3
  timeout:
    connect: 3s
    read: 3s
    write: 3s
    response: 3s
    global: 6s

retry:
  max-attempts: 3
  wait-duration: 1s
  retryable-codes: 500, 502, 503, 504, 429

resilience4j:
  circuitbreaker:
    instances:
      apiClient:
        sliding-window-size: 1
        minimum-number-of-calls: 1
        failure-rate-threshold: 100
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 5s

ratelimiter:
  capacity: 10
  refill-tokens: 10
  refill-duration: 1m

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scrapper
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:29092
      properties:
        spring.json.add.type.headers: false
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
