app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  kafka:
    updates-topic-name: updates
    group-id: bot
    dlq-group-id: bot-dlq

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: bot
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: backend.academy.bot.dto.LinkUpdate
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      bootstrap-servers: localhost:29092
    bootstrap-servers: localhost:29092

client:
  scrapper-url: http://localhost:8081
  timeout:
    connect: 3s
    read: 3s
    write: 3s
    response: 3s

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
